# Generated by Django 4.1 on 2022-08-18 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PortfolioLab', '0002_institution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quanitity', models.SmallIntegerField()),
                ('address', models.CharField(max_length=128)),
                ('phone_number', models.SmallIntegerField()),
                ('city', models.CharField(max_length=128)),
                ('zip_code', models.CharField(max_length=15)),
                ('pick_up_date', models.DateField(null=True)),
                ('pick_up_time', models.TimeField(null=True)),
                ('pick_up_comment', models.TextField()),
                ('categories', models.ManyToManyField(to='PortfolioLab.category')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PortfolioLab.institution')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
